version: '3.8'

services:
  vision_api:
    build: ./orchestrator-service
    container_name: vision_yolo_app
    ports:
      - "8000:8000"
    volumes:
      - ./orchestrator-service:/app
      
    restart: unless-stopped

  camera_service:
    build: ./camera-service
    container_name: camera_service
    ports:
      - "8001:8001"
    volumes:
      - ./camera-service:/app
      - ./dataset/capturas:/app/dataset/capturas/
    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    privileged: true
    restart: unless-stopped

  inference_service:
    #build: ./inference-service
    image: vision-yolo-services-inference_service:latest
    container_name: inference_service
    ports:
      - "8002:8002"
    volumes:
      - ./inference-service:/app
      - ./dataset:/app/dataset/
    restart: unless-stopped